name: 'idkyet builder'
description: 'builder for the idkyet linux project'
inputs:
  layer_config_file:
    description: 'layer config file'
    required: true
  out_dir:
    description: 'out directory'
    required: true
  version:
    description: 'version for release'
    required: true
  sb_db_key:
    description: 'secure_boot db key to sign efi'
    required: false
  sb_db_pem:
    description: 'secure_boot db pem to sign efi'
    required: false
#outputs:
#  hashes:
#    description: 'json dict of hashes of all files'
runs:
  using: "composite"
  steps:
    - name: Restore and build aur
      uses: ./aur
    - name: Build images
      uses: ./builder
    - name: Upload Packages
      run: |
        cd ${{ gitea.workspace }}/out
        for f in *;do
          echo "Uploading $f"
          du -sh $f
          curl --user "${{ gitea.actor }}:${{ secrets.PACKET_TOKEN }}" \
            --upload-file "$f" \
            "https://git.fml128.ch/api/packages/${{ github.repository_owner }}/generic/${GITHUB_REPOSITORY#*/}/${{ steps.version.outputs.RELEASE_VERSION }}/$f"
        done
    - name: If failure delete packages
      if: failure()
      run: |
        curl --user "${{ gitea.actor }}:${{ secrets.PACKET_TOKEN }}" \
          -X DELETE \
          "https://git.fml128.ch/api/packages/${{ github.repository_owner }}/generic/${GITHUB_REPOSITORY#*/}/${{ steps.version.outputs.RELEASE_VERSION }}"

