name: 'idkyet builder'
description: 'builder for the idkyet linux project'
inputs:
  layer_config_file:
    description: 'layer config file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate image
      uses: docker://git.fml128.ch/fml128/idkyet-builder:2025.06.111002
      with:
        args: validate ${{ inputs.layer_config_file }}