name: 'idkyet aur builder'
description: 'aur builder for the idkyet linux project'
inputs:
  layer_config_file:
    description: 'layer config file'
    required: true
#outputs:
#  hashes:
#    description: 'json dict of hashes of all files'
runs:
  using: "composite"
  steps:
    - name: Get aur cache key
      id: cache-aur-key
      uses: docker://git.fml128.ch/fml128/idkyet-builder:latest
      with:
        args: generate_aur_cache_key
    - name: Restore aur cache
      id: cache-aur-restore
      uses: https://code.forgejo.org/actions/cache/restore@v3
      with:
        path: aur
        key: aur-${{ github.repository }}-${{ steps.cache-aur-key.outputs.cache-aur-key }}
        restore-keys: aur-${{ github.repository }}-
    - name: Build aur
      if: steps.cache-aur-restore.outputs.cache-hit != 'true'
      uses: docker://git.fml128.ch/fml128/idkyet-builder:latest
      with:
        args: build_aur_packages
    - name: Save aur cache
      if: steps.cache-aur-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: aur
        key: aur-${{ github.repository }}-${{ steps.cache-aur-key.outputs.cache-aur-key }}
