name: 'idkyet builder'
description: 'builder for the idkyet linux project'
inputs:
  layer_config_file:
    description: 'layer config file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify image
      uses: docker://git.fml128.ch/fml128/idkyet-builder:2024.04.031632
      with:
        args: verify ${{ inputs.layer_config_file }}