name: 'idkyet builder'
description: 'builder for the idkyet linux project'
inputs:
  layer_config_file:
    description: 'layer config file'
    required: true
  out_dir:
    description: 'out directory'
    required: true
  version:
    description: 'version for release'
    required: true
  sb_db_key:
    description: 'secure_boot db key to sign efi'
    required: false
  sb_db_pem:
    description: 'secure_boot db pem to sign efi'
    required: false
  api_auth_token:
    description: 'api_auth_token if needed to download base images'
    required: false

#outputs:
#  hashes:
#    description: 'json dict of hashes of all files'
runs:
  using: "composite"
  steps:
    - name: Build image
      uses: docker://git.fml128.ch/fml128/idkyet-builder:2024.04.292045
      with:
        args: build ${{ inputs.layer_config_file }}
